---
#- include: server.yml

- name: install quassel
  hosts: all
  sudo: yes
  tasks:

    - name: install quasselcore
      apt: pkg=quassel-core state=latest

    - name: run quasselcore
      service: name=quasselcore state=started enabled=yes

    - name: give sqlite3 db to quasselcore user
      file: path=/var/lib/quassel/quassel-storage.sqlite owner=quasselcore group=quassel

    - name: open ufw ports for quasselcore, quassel-search-go
      command: ufw allow {{ item }}
      with_items:
        - 4242
        - 4243

- name: setup quassel-search-go
  hosts: all
  sudo: yes
  vars:
    installdir: /usr/local/quassel-search-go

    # can be sqlite3 or postgres
    dbtype: sqlite3

    # port that the web site runs on
    # TODO: extract this to group_vars? so it can be used above
    webport: 4243

    platforms:
      i386: 386
      x86_64: amd64
    platform: "{{ platforms[ansible_architecture] }}"
  tasks:

    - name: get quassel-search-go repo
      git:
        repo=https://github.com/grschafer/quassel-search-go.git
        dest={{ installdir }}

    - name: set binary executable
      file: path={{ installdir }}/quassel-search-go-{{ platform }} mode=775

    - name: copy upstart conf
      template:
        src=templates/quassel-search-go.conf.j2
        dest=/etc/init/quassel-search-go.conf
        mode=0644

    - name: set quassel-search-go settings
      template: src=templates/conf.gcfg.j2 dest={{ installdir }}/conf.gcfg

    - name: start quassel-search-go service
      service: name=quassel-search-go state=started enabled=yes
